# Generated by Django 6.0 on 2025-12-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
