# Generated by Django 6.0 on 2025-12-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_opportunity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
